## 00. PyTorch Fundamentals

[Resource notebook](https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__

'2.1.0+cu121'

In [ ]:
## GPU Used
!nvidia-smi

Thu Jan 18 14:05:05 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors

In [ ]:
## scalar

scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
scalar.ndim
scalar.shape

torch.Size([])

In [ ]:
scalar.item()

7

In [ ]:
matrix=torch.tensor([
    [7,8,4]
])
matrix.shape
matrix.dtype

torch.int64

In [ ]:
#TENSOR
tensor=torch.tensor([
    [[1,2,3],
     [3,6,9],
     [2,4,5]]
    ])
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4047, 0.2117, 0.4321, 0.6560],
        [0.0992, 0.3001, 0.9207, 0.0823],
        [0.8115, 0.5245, 0.1698, 0.8256]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) # height, width,colour channel

random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Zeros and ones

zeros=torch.zeros(size=(3,4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [ ]:
### Creating a range of tensors and tensors-like

torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
ten_zeroes=torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype is the tensor (e.g float32 or float16)
                             device=None, #cpu,cuda !IMPORTANT when operating with tensors (they should live in same device)
                             requires_grad=False)# wether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
## Default pytorch dtype is float32
float_32_tensor.dtype

torch.float16

In [ ]:
int_32_tensor= torch.tensor([3,6,9],dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype- to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
### Manipulating Tensors (tensor operations)

## Addition,Subtraction,Multiplication, Division, Matrix

In [ ]:
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
## Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
# Element wise multiplication (scalar x mat)
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
resulting_tensor=torch.matmul(torch.rand(2,4),torch.rand(4,3))
print(f"The shape is {resulting_tensor.shape} and the tensor is {resulting_tensor}")

The shape is torch.Size([2, 3]) and the tensor is tensor([[0.8237, 0.8936, 0.1876],
        [1.3370, 1.6782, 0.4182]])


In [ ]:
v=torch.tensor([[1,2,3],[4,5,6]]) # 2x3
w=torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # 3x3

# mat mul
u=torch.matmul(v,w)
u.shape

torch.Size([2, 3])

In [ ]:
### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication

a=torch.tensor(
    [[1,2],
     [3,4],
      [5,6]]
    )
b=torch.tensor(
    [[7,10],
     [8,11],
      [9,12]]
    )
## transpose one tensor
torch.mm(a,b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
##Finding min, max, mean, sum,etc (tensor aggregation)

x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the min

torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
# It has to be either floating or complex
torch.mean(x.type(torch.float32)),(x.type(torch.float32)).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum
# The sum of each individual tensor
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
#Argmax & argmean
#Find the position in tensor that has the mini value with argmin()-> return the index position
print(x)
x.argmin()

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


tensor(0)

In [ ]:
#Find the position in tensor that has the maximum value with argmax()

x[x.argmax().item()]


tensor(90)

#Reshaping,stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking- Combine multiple tensors on top of each other
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1`dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#Shares the memory
z= x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)

z[:,0]=5
z,x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x.shape

torch.Size([9])

In [ ]:
#Stack tensors on top of each other
x_stacked=torch.stack([x,x,x],dim=0)
x_stacked


tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor

x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:

x_reshaped.shape

torch.Size([9, 1])

In [ ]:
#Squeeze method removes all dim=1
x_squeezed = x_reshaped.squeeze()

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim

print(f"Previous target: {x_squeezed}")

x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


## Permute

* `torch.permute` - rearranges the dimension of a target tensor in a specifcied order

Returns a view of the original tensor input with its dimensions permuted.

**Parameters**

* Input ( Tensor) the input tensor
* dims (tuple of int) the desired ordering of dimensions

In [ ]:
# Example

u = torch.randn(size=(224,224,3)) #[height,width,color_channel]

print(f"\nOriginal Tensor shape: {u.shape}")

## Permute the original tensor to rearrange the axis (or dim)
u_permuted=u.permute((2,0,1)) #shift axis 0->1, 1 -> 2 , 2->0
print(f"\nPermuted tensor shape: {u_permuted.shape}")


Original Tensor shape: torch.Size([224, 224, 3])

Permuted tensor shape: torch.Size([3, 224, 224])


In [ ]:
#Lets create a matrix

A=torch.randn(2,4)
print(A)

print(A.permute(1,0)) ##  In matrixes its the sames as transpose

tensor([[ 1.8684, -0.9884,  0.7644, -0.1803],
        [ 2.1373, -1.1118, -0.1165,  0.5025]])
tensor([[ 1.8684,  2.1373],
        [-0.9884, -1.1118],
        [ 0.7644, -0.1165],
        [-0.1803,  0.5025]])


In [ ]:
#Indexing (selecting data from tensors)
import torch

x=torch.arange(1,10).shape
x

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor

import torch

x = torch.arange(1,10).reshape(1,3,3)

x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0] # 0 dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [ ]:
# Index inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Index on x to return 9

x[0,2,2]

tensor(9)

In [ ]:
# Index on x to return 3,6,9

x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy


In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor= torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor = torch.ones(7)
numpy_tensor= tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural networks leanrs:

`star with random numbers -> tensor operations -> update random numbers to trhy and make them better representations of the data -> again -> again -> again... `

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.3359, 0.7172, 0.7120, 0.8968],
        [0.0059, 0.1063, 0.8234, 0.4127],
        [0.3882, 0.0915, 0.5480, 0.3842]])
tensor([[0.9737, 0.9244, 0.0968, 0.9655],
        [0.3515, 0.2291, 0.5634, 0.3544],
        [0.9781, 0.1210, 0.7149, 0.9248]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
## Make some random but reproducible tensors


RANDOM_SEED=42 #flavour of randomness
torch.manual_seed(RANDOM_SEED)

random_tensor_C= torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
